#!/bin/bash

# create configure file based on envs

[ -f /root/nghttpx.conf ] && rm /root/nghttpx.conf
cat >/root/nghttpx.conf <<EOL
http2-proxy=yes
frontend=0.0.0.0,8080;no-tls
backend=$H2_BACKEND
client-cert-file=/key/$H2_CERT
client-private-key-file=/root/$H2_KEY
workers=$H2_WORKERS
add-x-forwarded-for=no
no-via=yes
no-ocsp=yes
npn-list=h2
EOL

chmod 0600 /key/$H2_CERT
mv /key/$H2_KEY /root/$H2_KEY
chmod 0600 /root/$H2_KEY

/usr/sbin/nghttpx --conf=/root/nghttpx.conf $H2_PARAMS